//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hoteLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDepartment
    {
        public int ID_Sale { get; set; }
        public Nullable<int> Reservation_ID { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
